/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToaster: typeof import('./components/AppToaster.vue')['default']
    CopiedTextTab: typeof import('./components/CopiedTextTab.vue')['default']
    CustomCard: typeof import('./components/CustomCard.vue')['default']
    CustomTabs: typeof import('./components/CustomTabs.vue')['default']
    DsfrAccordion: typeof import('@gouvminint/vue-dsfr')['DsfrAccordion']
    DsfrAccordionsGroup: typeof import('@gouvminint/vue-dsfr')['DsfrAccordionsGroup']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrCallout: typeof import('@gouvminint/vue-dsfr')['DsfrCallout']
    DsfrFileUpload: typeof import('@gouvminint/vue-dsfr')['DsfrFileUpload']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrInput: typeof import('@gouvminint/vue-dsfr')['DsfrInput']
    DsfrInputGroup: typeof import('@gouvminint/vue-dsfr')['DsfrInputGroup']
    DsfrSelect: typeof import('@gouvminint/vue-dsfr')['DsfrSelect']
    DsfrTile: typeof import('@gouvminint/vue-dsfr')['DsfrTile']
    ParamsResume: typeof import('./components/ParamsResume.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    ResumeInfoBulle: typeof import('./components/ResumeInfoBulle.vue')['default']
    ResumeResult: typeof import('./components/ResumeResult.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    UploadDocumentTab: typeof import('./components/UploadDocumentTab.vue')['default']
    UrlTab: typeof import('./components/UrlTab.vue')['default']
  }
}
