/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppChatbot: typeof import('./components/AppChatbot.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppToaster: typeof import('./components/AppToaster.vue')['default']
    ChatTaskFilterModal: typeof import('./components/ChatTaskFilterModal.vue')['default']
    ClassificationTab: typeof import('./components/ClassificationTab.vue')['default']
    CopiedTextTab: typeof import('./components/CopiedTextTab.vue')['default']
    copy: typeof import('./components/StatModel copy.vue')['default']
    CustomCard: typeof import('./components/CustomCard.vue')['default']
    CustomTabs: typeof import('./components/CustomTabs.vue')['default']
    DsfrAccordion: typeof import('@gouvminint/vue-dsfr')['DsfrAccordion']
    DsfrAccordionsGroup: typeof import('@gouvminint/vue-dsfr')['DsfrAccordionsGroup']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrButtonGroup: typeof import('@gouvminint/vue-dsfr')['DsfrButtonGroup']
    DsfrCallout: typeof import('@gouvminint/vue-dsfr')['DsfrCallout']
    DsfrCheckbox: typeof import('@gouvminint/vue-dsfr')['DsfrCheckbox']
    DsfrDropdown: typeof import('./components/DsfrDropdown.vue')['default']
    DsfrFileUpload: typeof import('@gouvminint/vue-dsfr')['DsfrFileUpload']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrInput: typeof import('@gouvminint/vue-dsfr')['DsfrInput']
    DsfrInputGroup: typeof import('@gouvminint/vue-dsfr')['DsfrInputGroup']
    DsfrSelect: typeof import('@gouvminint/vue-dsfr')['DsfrSelect']
    DsfrTile: typeof import('@gouvminint/vue-dsfr')['DsfrTile']
    FileParamsModal: typeof import('./components/FileParamsModal.vue')['default']
    LeaderboardModal: typeof import('./components/LeaderboardModal.vue')['default']
    ParamsResume: typeof import('./components/ParamsResume.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    ResumeInfoBulle: typeof import('./components/ResumeInfoBulle.vue')['default']
    ResumeResult: typeof import('./components/ResumeResult.vue')['default']
    ResumeResultModal: typeof import('./components/ResumeResultModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    StatModel: typeof import('./components/StatModel.vue')['default']
    TasksTab: typeof import('./components/TasksTab.vue')['default']
    TaskTab: typeof import('./components/TaskTab.vue')['default']
    UploadDocumentTab: typeof import('./components/UploadDocumentTab.vue')['default']
    UrlTab: typeof import('./components/UrlTab.vue')['default']
  }
}

// For TSX support
declare global {
  const AppChatbot: typeof import('./components/AppChatbot.vue')['default']
  const AppFooter: typeof import('./components/AppFooter.vue')['default']
  const AppHeader: typeof import('./components/AppHeader.vue')['default']
  const AppToaster: typeof import('./components/AppToaster.vue')['default']
  const ChatTaskFilterModal: typeof import('./components/ChatTaskFilterModal.vue')['default']
  const ClassificationTab: typeof import('./components/ClassificationTab.vue')['default']
  const CopiedTextTab: typeof import('./components/CopiedTextTab.vue')['default']
  const copy: typeof import('./components/StatModel copy.vue')['default']
  const CustomCard: typeof import('./components/CustomCard.vue')['default']
  const CustomTabs: typeof import('./components/CustomTabs.vue')['default']
  const DsfrAccordion: typeof import('@gouvminint/vue-dsfr')['DsfrAccordion']
  const DsfrAccordionsGroup: typeof import('@gouvminint/vue-dsfr')['DsfrAccordionsGroup']
  const DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
  const DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
  const DsfrButtonGroup: typeof import('@gouvminint/vue-dsfr')['DsfrButtonGroup']
  const DsfrCallout: typeof import('@gouvminint/vue-dsfr')['DsfrCallout']
  const DsfrCheckbox: typeof import('@gouvminint/vue-dsfr')['DsfrCheckbox']
  const DsfrDropdown: typeof import('./components/DsfrDropdown.vue')['default']
  const DsfrFileUpload: typeof import('@gouvminint/vue-dsfr')['DsfrFileUpload']
  const DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
  const DsfrInput: typeof import('@gouvminint/vue-dsfr')['DsfrInput']
  const DsfrInputGroup: typeof import('@gouvminint/vue-dsfr')['DsfrInputGroup']
  const DsfrSelect: typeof import('@gouvminint/vue-dsfr')['DsfrSelect']
  const DsfrTile: typeof import('@gouvminint/vue-dsfr')['DsfrTile']
  const FileParamsModal: typeof import('./components/FileParamsModal.vue')['default']
  const LeaderboardModal: typeof import('./components/LeaderboardModal.vue')['default']
  const ParamsResume: typeof import('./components/ParamsResume.vue')['default']
  const ProgressBar: typeof import('./components/ProgressBar.vue')['default']
  const ResumeInfoBulle: typeof import('./components/ResumeInfoBulle.vue')['default']
  const ResumeResult: typeof import('./components/ResumeResult.vue')['default']
  const ResumeResultModal: typeof import('./components/ResumeResultModal.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SideBar: typeof import('./components/SideBar.vue')['default']
  const StatModel: typeof import('./components/StatModel.vue')['default']
  const TasksTab: typeof import('./components/TasksTab.vue')['default']
  const TaskTab: typeof import('./components/TaskTab.vue')['default']
  const UploadDocumentTab: typeof import('./components/UploadDocumentTab.vue')['default']
  const UrlTab: typeof import('./components/UrlTab.vue')['default']
}