/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/metrics': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Metrics
     * @description Endpoint that serves Prometheus metrics.
     */
    get: operations['metrics_metrics_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Healthcheck */
    get: operations['healthcheck_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/task/text-url': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Summarize Content */
    post: operations['summarize_content_api_task_text_url_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/task/text-url': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** New Summarize Content */
    post: operations['new_summarize_content_api_v1_task_text_url_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/task/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read */
    get: operations['read_api_task__id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/task/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Task */
    get: operations['get_task_api_v1_task__id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/task/user/{user_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read User */
    get: operations['read_user_api_task_user__user_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/task/user/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Tasks Read User */
    get: operations['get_tasks_read_user_api_v1_task_user__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/task/document': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Summarize Doc */
    post: operations['summarize_doc_api_task_document_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/task/document': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** New Summarize Doc */
    post: operations['new_summarize_doc_api_v1_task_document_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** Body_new_summarize_doc_api_v1_task_document_post */
    Body_new_summarize_doc_api_v1_task_document_post: {
      /**
       * File
       * Format: binary
       */
      file: string
      /**
       * Prompt
       * @description Custom prompt for after summary
       */
      prompt?: string | null
      /**
       * Parameters
       * @description Parameters {'temperature': 0.0, 'language': 'French', 'size': 4000, 'extras': {}, 'method': 'map_reduce', 'custom_prompt': None}
       * @default
       */
      parameters: string | null
      /**
       * Extras
       * @description Extras json payload
       * @default
       */
      extras: string | null
    }
    /** Body_summarize_doc_api_task_document_post */
    Body_summarize_doc_api_task_document_post: {
      /**
       * File
       * Format: binary
       */
      file: string
      /**
       * User Id
       * @description User id
       */
      user_id: string
      /**
       * Prompt
       * @description Custom prompt for after summary
       */
      prompt?: string | null
      /**
       * Parameters
       * @description Parameters {'temperature': 0.0, 'language': 'French', 'size': 4000, 'extras': {}, 'method': 'map_reduce', 'custom_prompt': None}
       * @default
       */
      parameters: string | null
      /**
       * Extras
       * @description Extras json payload
       * @default
       */
      extras: string | null
    }
    /** Content */
    Content: {
      /** Prompt */
      prompt?: string | null
      /** Extras */
      extras?: {
        [key: string]: unknown
      } | null
    }
    /** DocumentModel */
    DocumentModel: {
      /**
       * Type
       * @default document
       */
      type: string
      /** Created At */
      created_at: number
      /** Extras */
      extras?: {
        [key: string]: unknown
      } | null
      /** File Path */
      file_path: string
      /** Raw Filename */
      raw_filename: string
      /** Content Type */
      content_type: string
      /** Ext */
      ext: string
      /** Size */
      size: number
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * HealtStatus
     * @enum {string}
     */
    HealtStatus: 'healthy' | 'unhealthy'
    /** Health */
    Health: {
      /**
       * Name
       * @description Api name
       */
      name: string
      /**
       * Version
       * @description version name
       */
      version: string
      /**
       * Up Time
       * @description Since up time name
       */
      up_time: string
      /**
       * Extras
       * @description Any extras informations
       */
      extras?: {
        [key: string]: unknown
      } | null
      /**
       * @description Status of the api
       * @default healthy
       */
      status: components['schemas']['HealtStatus']
      /**
       * Dependencies
       * @description List of dependencies of the api
       */
      dependencies?: components['schemas']['Health'][] | null
    }
    /** Input */
    Input: {
      /**
       * Content
       * @default {}
       */
      content: components['schemas']['UrlContent'] | components['schemas']['TextContent'] | components['schemas']['Content'] | null
      parameters?: components['schemas']['SummaryParameters'] | null
    }
    /** InputModel */
    InputModel: {
      /** User Id */
      user_id: string
      /**
       * Content
       * @default {}
       */
      content: components['schemas']['UrlContent'] | components['schemas']['TextContent'] | components['schemas']['Content'] | null
      parameters?: components['schemas']['SummaryParameters'] | null
    }
    /** PartialSummary */
    PartialSummary: {
      /** Id */
      id: string
      /** Text */
      text: string
      /** Word Count */
      word_count: number
      text1: components['schemas']['Text']
      text2: components['schemas']['Text']
    }
    /** ResultModel */
    ResultModel: {
      /** Type */
      type: string
      /** Created At */
      created_at: number
      /** Model Name */
      model_name: string
      /** Model Version */
      model_version: string
      /** Updated At */
      updated_at?: number | null
      /**
       * Texts Found
       * @default []
       */
      texts_found: string[] | null
      /**
       * Percentage
       * @default 0
       */
      percentage: number
      /** Extras */
      extras?: {
        [key: string]: unknown
      } | null
    }
    /** SummaryModel */
    SummaryModel: {
      /**
       * Type
       * @default summary
       */
      type: string
      /** Created At */
      created_at: number
      /** Model Name */
      model_name: string
      /** Model Version */
      model_version: string
      /** Updated At */
      updated_at?: number | null
      /**
       * Texts Found
       * @default []
       */
      texts_found: string[] | null
      /**
       * Percentage
       * @default 0
       */
      percentage: number
      /** Extras */
      extras?: {
        [key: string]: unknown
      } | null
      /** Summary */
      summary: string
      /** Word Count */
      word_count: number
      /**
       * Nb Llm Calls
       * @default 0
       */
      nb_llm_calls: number | null
      /**
       * Partial Summaries
       * @default []
       */
      partial_summaries: (components['schemas']['PartialSummary'] | components['schemas']['Text'])[] | null
    }
    /** SummaryParameters */
    SummaryParameters: {
      /**
       * Temperature
       * @description Temperature of the model
       * @default 0
       */
      temperature: number | null
      /**
       * Language
       * @description Language you want the summary
       * @default French
       */
      language: string | null
      /**
       * Size
       * @description Number of words you, WARNING: the model will try to get less than the size
       * @default 4000
       */
      size: number | null
      /**
       * Extras
       * @description Extras informations
       */
      extras?: {
        [key: string]: unknown
      } | null
      /**
       * Method
       * @default map_reduce
       */
      method: ('map_reduce' | 'refine' | 'text_rank' | 'k-means' | 'stuff') | null
      /**
       * Custom Prompt
       * @description Custom prompt you want after the sumup
       */
      custom_prompt?: string | null
    }
    /** TaskModel */
    TaskModel: {
      /** Id */
      id: string
      /** User Id */
      user_id: string
      /** Type */
      type: string
      /**
       * Status
       * @default queued
       */
      status: string
      /** Percentage */
      percentage?: number | null
      /** Input */
      input?: components['schemas']['URLModel'] | components['schemas']['DocumentModel'] | components['schemas']['TextModel'] | null
      /** Output */
      output?: components['schemas']['ResultModel'] | components['schemas']['SummaryModel'] | null
      /**
       * @default {
       *       "temperature": 0,
       *       "language": "French",
       *       "size": 4000,
       *       "extras": {},
       *       "method": "map_reduce"
       *     }
       */
      parameters: components['schemas']['SummaryParameters'] | null
      /** Position */
      position?: number | null
      /** Created At */
      created_at: number
      /** Updated At */
      updated_at: number
      /** Extras */
      extras?: {
        [key: string]: unknown
      } | null
    }
    /** Text */
    Text: {
      /** Id */
      id: string
      /** Text */
      text: string
      /** Word Count */
      word_count: number
    }
    /** TextContent */
    TextContent: {
      /** Prompt */
      prompt?: string | null
      /** Extras */
      extras?: {
        [key: string]: unknown
      } | null
      /** Text */
      text: string
    }
    /** TextModel */
    TextModel: {
      /**
       * Type
       * @default texte
       */
      type: string
      /** Created At */
      created_at: number
      /** Extras */
      extras?: {
        [key: string]: unknown
      } | null
      /** Text */
      text: string
    }
    /** URLModel */
    URLModel: {
      /**
       * Type
       * @default url
       */
      type: string
      /** Created At */
      created_at: number
      /** Extras */
      extras?: {
        [key: string]: unknown
      } | null
      /** Url */
      url: string
    }
    /** UrlContent */
    UrlContent: {
      /** Prompt */
      prompt?: string | null
      /** Extras */
      extras?: {
        [key: string]: unknown
      } | null
      /** Url */
      url: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  metrics_metrics_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  healthcheck_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
    }
  }
  summarize_content_api_task_text_url_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['InputModel']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskModel']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  new_summarize_content_api_v1_task_text_url_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Input']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskModel']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  read_api_task__id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskModel']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_task_api_v1_task__id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskModel']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  read_user_api_task_user__user_id__get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskModel'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_tasks_read_user_api_v1_task_user__get: {
    parameters: {
      query?: {
        offset?: number
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskModel'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  summarize_doc_api_task_document_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_summarize_doc_api_task_document_post']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskModel']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  new_summarize_doc_api_v1_task_document_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_new_summarize_doc_api_v1_task_document_post']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskModel']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
