"""add group_id and content_hash

Revision ID: 6fdb21e394c9
Revises: 27cd95557285
Create Date: 2025-08-15 08:41:20.245461

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6fdb21e394c9"
down_revision: Union[str, None] = "27cd95557285"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("group_id", sa.String(), nullable=True))
    op.add_column("tasks", sa.Column("content_hash", sa.String(), nullable=True))
    op.create_index(op.f("ix_tasks_content_hash"), "tasks", ["content_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_content_hash"), table_name="tasks")
    op.drop_column("tasks", "content_hash")
    op.drop_column("tasks", "group_id")
    # ### end Alembic commands ###
