FROM python:3.11.9-slim-bookworm

RUN apt-get update \
    && apt-get install build-essential -y \
    && apt-get purge -y --auto-remove \
    && rm -rf /var/lib/apt/lists/*

EXPOSE $BACKEND_PORT

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1


# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Copy all the packages, as this container should be used for dev
WORKDIR /app
COPY . .

WORKDIR /app/abrege_api

ENV POETRY_VIRTUALENVS_CREATE=false
RUN pip install poetry
RUN poetry lock && poetry install --with dev

CMD [ "bash", "run.sh" ]