name: Lint

on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        description: Python version used to run tests
        required: true
        type: string
      run-backend:
        description: Run backend tests
        required: false
        type: boolean
        default: true
      run-sdk:
        description: Run SDK tests  
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      PYTHON_VERSION:
        description: Python version used to run tests
        required: true
        type: string
        default: 3.X

jobs:
  tests:
    name: Lint code
    runs-on: ubuntu-24.04
    if: inputs.run-backend == true || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run lint
        run: make lint
  lint-sdk:
    name: Lint SDK code
    runs-on: ubuntu-24.04
    if: inputs.run-sdk == true || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run lint on SDK
        run: make lint-sdk